import * as assert from 'assert';
import { SqliteClient } from '../../db/sqliteClient';
import { getTestProjectPath, hasTestProjectSqliteDb } from '../test-project-helpers';

suite('SqliteClient Unit Tests', () => {
    const projectPath = getTestProjectPath('runnable');
    let client: SqliteClient;

    suiteSetup(function () {
        if (!hasTestProjectSqliteDb('runnable')) {
            // The fixture databases are generated by `npm run test:fixtures` (part of the
            // `pretest` hook). Skip gracefully if they haven't been generated yet.
            this.skip();
        }
        client = new SqliteClient();
        client.open(projectPath);
    });

    suiteTeardown(() => {
        client?.close();
    });

    test('open() connects successfully and isOpen reflects state', () => {
        assert.strictEqual(client.isOpen, true);
    });

    test('getAllDpTypes() returns rows with expected fields', () => {
        const dpTypes = client.getAllDpTypes();

        assert.ok(dpTypes.length > 0, 'expected at least one datapoint type');
        for (const dpt of dpTypes) {
            assert.strictEqual(typeof dpt.dpt_id, 'number');
            assert.strictEqual(typeof dpt.canonical_name, 'string');
            assert.strictEqual(typeof dpt.next_free_el_id, 'number');
            assert.strictEqual(typeof dpt.modification_time, 'number');
        }

        const names = dpTypes.map((d) => d.canonical_name);
        assert.ok(names.includes('ExampleDP_Float'), 'expected ExampleDP_Float in fixture');
    });

    test('getElementsByDptId() returns elements for a known DPT', () => {
        const dpTypes = client.getAllDpTypes();
        const floatDpt = dpTypes.find((d) => d.canonical_name === 'ExampleDP_Float');
        assert.ok(floatDpt, 'fixture must contain ExampleDP_Float');

        const elements = client.getElementsByDptId(floatDpt!.dpt_id);
        assert.ok(elements.length > 0, 'expected at least one element');

        const valueEl = elements.find((e) => e.canonical_name === 'value');
        assert.ok(valueEl, 'expected a "value" element for ExampleDP_Float');
        assert.strictEqual(typeof valueEl!.el_id, 'number');
        assert.strictEqual(typeof valueEl!.datatype, 'number');
    });

    test('getLastValue() casts 64-bit columns to strings and returns the stored value', () => {
        // From scripts/create-test-fixtures.js: dp_id=1, el_id=2 -> value '42.5', variable_type=4
        const lastValue = client.getLastValue(1, 2);

        assert.ok(lastValue, 'expected a last_value row for dp_id=1, el_id=2');
        assert.strictEqual(lastValue!.value, '42.5');
        assert.strictEqual(typeof lastValue!.original_time, 'string');
        assert.strictEqual(typeof lastValue!.status_64, 'string');
        // Must be a numeric string (CAST(... AS TEXT)), not e.g. "[object Object]"
        assert.ok(/^\d+$/.test(lastValue!.original_time as unknown as string));
        assert.ok(/^\d+$/.test(lastValue!.status_64 as unknown as string));
    });

    test('getSystemName() returns a string when available, or undefined', () => {
        // Note: scripts/create-test-fixtures.js does not currently create a `system`
        // table, so this may throw ("no such table: system") on the generated fixture.
        // Assert the shape defensively rather than a specific fixture value.
        let systemName: string | undefined;
        try {
            systemName = client.getSystemName();
        } catch {
            systemName = undefined;
        }

        if (systemName !== undefined) {
            assert.strictEqual(typeof systemName, 'string');
        }
    });

    test('rows returned by node:sqlite are null-prototype objects, but JSON/spread-safe', () => {
        const dpTypes = client.getAllDpTypes();
        assert.ok(dpTypes.length > 0);
        const row = dpTypes[0];

        // Documents the node:sqlite quirk: rows are Object.create(null), not object literals.
        assert.strictEqual(Object.getPrototypeOf(row), null);

        // Still safe to JSON.stringify or spread.
        const roundTripped = JSON.parse(JSON.stringify(row)) as Record<string, unknown>;
        assert.deepStrictEqual(roundTripped, { ...row });
    });

    test('close() disconnects and isOpen becomes false', () => {
        const other = new SqliteClient();
        other.open(projectPath);
        assert.strictEqual(other.isOpen, true);

        other.close();
        assert.strictEqual(other.isOpen, false);
    });
});
